server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8081
  shutdown: graceful

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://217.15.165.146:3306/crawling?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: ms38559851!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  mvc:
    static-path-pattern: "/static/**"

logging:
  level:
    '[com.see.realview]': DEBUG
    '[org.hibernate.type]': TRACE
  pattern:
    dateformat: yyyy-MM-dd | HH:mm:ss.SSS |, Asia/Seoul
